# Generated by Django 4.0.5 on 2022-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
    ]
